# Generated by Django 5.0.4 on 2024-05-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_alter_human_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='image',
            field=models.ImageField(blank=True, default='def.png', null=True, upload_to='new_image/'),
        ),
    ]
